# Generated by Django 5.0.6 on 2024-06-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_tblstudents_classroom_tblstudents_classrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblstudents',
            name='classrooms',
            field=models.ManyToManyField(null=True, related_name='students', to='authentication.classroom'),
        ),
        migrations.AlterField(
            model_name='tblstudents',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$9Q3J4OLXqPwtiO0rVrZ04G$t254EYm+x6w0YISRPrXM6wJOgAbrSUsuxDnzMasZ+Wo=', max_length=128),
        ),
    ]
